# -*- coding: utf-8 -*-
"""
Figure Artist Coordinate Extraction & Parity Validation.
Extracts (x, y) coordinates directly from matplotlib Figure artists generated by
generate_publication_figures.create_publication_figure() and validates exact parity against CALIBRATION_RECORDS.
"""

import sys
from pathlib import Path
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

backend_dir = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(backend_dir))
sys.path.insert(0, str(backend_dir / "scripts"))

from app.services.delta_ml_corrector import CALIBRATION_RECORDS, get_delta_ml_corrector
from generate_publication_figures import create_publication_figure


def extract_and_verify_artists():
    corrector = get_delta_ml_corrector()
    
    # 1. Canonical data from CALIBRATION_RECORDS
    canonical_data = {}
    for r in CALIBRATION_RECORDS:
        pbe, target, chi, r_rat, z_avg, eps, formula, src, mp_id, fam = r
        feat = corrector._make_features(pbe, chi, r_rat, z_avg, eps)
        pred_delta = float(corrector.model.predict(feat.reshape(1, -1))[0])
        pred_gap = pbe + pred_delta
        canonical_data[formula] = {
            "pbe": pbe,
            "target": target,
            "pred": pred_gap,
            "family": fam,
        }

    # 2. Obtain real Figure object from generate_publication_figures
    fig = create_publication_figure()
    ax_a = fig.axes[0]
    panel_title = ax_a.get_title()

    # 3. Extract scatter point offsets directly from ax_a PathCollections
    extracted_points = []
    for child in ax_a.get_children():
        if isinstance(child, matplotlib.collections.PathCollection):
            offsets = child.get_offsets()
            if len(offsets) > 0:
                for pt in offsets:
                    extracted_points.append((float(pt[0]), float(pt[1])))

    print("=" * 85)
    print("FIGURE ARTIST EXTRACTION & EXACT NUMERICAL PARITY AUDIT")
    print("=" * 85)
    print(f"Figure Panel (a) Title: '{panel_title}'")
    print("Panel Type: In-Sample Calibration Parity (Model fit on full n=21 benchmark dataset)")
    print(f"Total Scatter Artist Points Extracted: {len(extracted_points)}")
    print()

    extracted_x = np.array([pt[0] for pt in extracted_points])
    extracted_y = np.array([pt[1] for pt in extracted_points])

    print("Extracted Artist x-coordinates (Reference Targets, eV):")
    print(np.array2string(extracted_x, precision=3, separator=", "))
    print()
    print("Extracted Artist y-coordinates (Delta-ML Corrected Gaps, eV):")
    print(np.array2string(extracted_y, precision=4, separator=", "))
    print()

    # Match extracted points to formulas by (target, pred) coordinates
    print(f"{'Formula':10s} | {'Plotted Ref x':13s} {'Canonical Target':16s} | {'Plotted Pred y':14s} {'Canonical Pred':14s} | Discrepancy (eV)")
    print("-" * 95)
    
    max_diff_x = 0.0
    max_diff_y = 0.0

    for formula, d in canonical_data.items():
        # Find matching point in extracted_points
        best_match = None
        min_dist = float("inf")
        for pt in extracted_points:
            dist = (pt[0] - d["target"]) ** 2 + (pt[1] - d["pred"]) ** 2
            if dist < min_dist:
                min_dist = dist
                best_match = pt

        assert best_match is not None, f"No matching point for {formula}"
        diff_x = abs(best_match[0] - d["target"])
        diff_y = abs(best_match[1] - d["pred"])
        max_diff_x = max(max_diff_x, diff_x)
        max_diff_y = max(max_diff_y, diff_y)

        print(f"{formula:10s} | {best_match[0]:13.3f} {d['target']:16.3f} | {best_match[1]:14.4f} {d['pred']:14.4f} | dx={diff_x:.1e}, dy={diff_y:.1e}")

    print("-" * 95)
    print(f"Max absolute discrepancy in x (Ref Target):     {max_diff_x:.2e} eV")
    print(f"Max absolute discrepancy in y (Delta-ML Pred):  {max_diff_y:.2e} eV")
    
    if max_diff_x < 1e-5 and max_diff_y < 1e-5:
        print("[VERIFICATION PASSED] Matplotlib figure artists exhibit 100% exact numerical parity with CALIBRATION_RECORDS.")
    else:
        raise ValueError("Figure artist discrepancy exceeds tolerance!")


if __name__ == "__main__":
    extract_and_verify_artists()
