# -*- coding: utf-8 -*-
"""
Provenance Audit and Quantum ESPRESSO Calculation for MAPbX3 (Item 1).

1. Provenance of prior draft PBE values:
   - In Mosconi et al., J. Phys. Chem. C 2013, 117, 13902 Table 1:
     Calculated PBE gaps: MAPbI3 = 1.57 eV, MAPbBr3 = 1.80 eV, MAPbCl3 = 2.34 eV.
     Experimental optical gaps: MAPbI3 = 1.55 eV, MAPbBr3 = 2.00 / 2.33 eV, MAPbCl3 = 3.11 eV.
   - Prior draft incorrectly placed 1.55 (experimental) in the PBE column, used an unverified
     linear interpolation 1.90, and an estimate 2.45.
   - None of those numbers were pipeline QE runs with a real MA cation (C, N, H atoms).

2. Recomputes / audits MAPbX3 series with full pipeline QE at Mosconi experimental geometries:
   - MAPbI3: a = 6.33 Å (Mosconi Table 1: 6.329 Å) -> PBE gap = 1.3787 eV
   - MAPbBr3: a = 5.90 Å (Mosconi Table 1: 5.895 Å) -> PBE gap = 1.5954 eV
   - MAPbCl3: a = 5.68 Å (Mosconi Table 1: 5.675 Å) -> PBE gap = 2.0994 eV

3. Evaluates LOOCV under both choices:
   - Choice A (Recomputed Pipeline QE, n=6 Pb-only)
   - Choice B (Mosconi Literature PBE, n=6 Pb-only)
   - Choice C (Dropping MAPbX3 entirely, n=3 CsPbX3 only)
"""

import os
import sys
import json
import time
from pathlib import Path
import numpy as np

# Ensure backend root is on sys.path
backend_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if backend_dir not in sys.path:
    sys.path.insert(0, backend_dir)

scripts_dir = os.path.dirname(__file__)
if scripts_dir not in sys.path:
    sys.path.insert(0, scripts_dir)

from pymatgen.core import Structure, Lattice
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import LeaveOneOut

from run_heldout_qe import build_ma_perovskite


def get_mapb_structures():
    return {
        "MAPbI3": {
            "structure": build_ma_perovskite("Pb", "I", 6.33),
            "a_cubic_angstrom": 6.33,
            "target_exp_gap_eV": 1.57,
            "mosconi_calculated_pbe_eV": 1.57,
            "prior_draft_pbe_eV": 1.55,
            "citation": "Mosconi et al., J. Phys. Chem. C 117, 13902 (2013) Table 1 (a=6.329 A)",
        },
        "MAPbBr3": {
            "structure": build_ma_perovskite("Pb", "Br", 5.90),
            "a_cubic_angstrom": 5.90,
            "target_exp_gap_eV": 2.33,
            "mosconi_calculated_pbe_eV": 1.80,
            "prior_draft_pbe_eV": 1.90,
            "citation": "Mosconi et al., J. Phys. Chem. C 117, 13902 (2013) Table 1 (a=5.895 A)",
        },
        "MAPbCl3": {
            "structure": build_ma_perovskite("Pb", "Cl", 5.68),
            "a_cubic_angstrom": 5.68,
            "target_exp_gap_eV": 3.11,
            "mosconi_calculated_pbe_eV": 2.34,
            "prior_draft_pbe_eV": 2.45,
            "citation": "Mosconi et al., J. Phys. Chem. C 117, 13902 (2013) Table 1 (a=5.675 A)",
        },
    }


def run_or_load_mapb_qe(force_rerun: bool = False):
    results_path = Path(backend_dir) / "scripts" / "mapb_qe_results.json"
    results = {}
    if not force_rerun and results_path.exists():
        with open(results_path, "r", encoding="utf-8") as f:
            results = json.load(f)

    structures_meta = get_mapb_structures()

    print("================================================================================")
    print("ITEM 1: MA PBE PROVENANCE AUDIT & STRUCTURES")
    print("================================================================================")
    print("Prior draft PBE values for MAPbI3/Br3/Cl3 were 1.55 / 1.90 / 2.45 eV.")
    print("Provenance Analysis:")
    print("  - MAPbI3 1.55 eV: Transcribed from Mosconi 2013 Table 1 *experimental* optical gap (1.55 eV),")
    print("    misfiled into the PBE column. Mosconi's calculated PBE was 1.57 eV.")
    print("  - MAPbBr3 1.90 eV: Heuristic interpolation; absent from Mosconi Table 1 (which gives PBE 1.80 eV).")
    print("  - MAPbCl3 2.45 eV: Heuristic estimate; absent from Mosconi Table 1 (which gives PBE 2.34 eV).")
    print("  - None were generated by our Quantum ESPRESSO pipeline with explicit MA cations.")
    print("================================================================================\n")

    for formula, meta in structures_meta.items():
        s = meta["structure"]
        poscar_str = s.to(fmt="poscar")
        print(f"--- CANDIDATE: {formula} ---")
        print(f"Geometry: Cubic a = {meta['a_cubic_angstrom']} A | Explicit Atoms: {len(s)} sites (Pb, 3 X, C, N, 6 H)")
        print(f"Citation: {meta['citation']}")
        print(f"Mosconi Reported PBE: {meta['mosconi_calculated_pbe_eV']} eV | Prior Draft PBE: {meta['prior_draft_pbe_eV']} eV")
        print("POSCAR EXECUTED BY QE:")
        print(poscar_str.strip())
        print("--------------------------------------------------------------------------------\n")

        if not force_rerun and formula in results and results[formula].get("status") == "success":
            print(f"[CACHED QE RUN] {formula}: PBE gap = {results[formula]['pbe_gap_eV']} eV ({results[formula]['gap_type']}) in {results[formula]['runtime_seconds']}s\n")
        else:
            from app.services.dft_validation import get_dft_service
            dft_service = get_dft_service()
            print(f"Executing live Quantum ESPRESSO PBE calculation for {formula}...")
            t0 = time.time()
            res = dft_service.run_pbe_pipeline(s, formula, fast_mode=True, kpt_dist=0.35)
            dt = time.time() - t0
            pbe_gap = res.get("pbe_gap_eV")
            gap_type = res.get("gap_type", "unknown")
            status = res.get("status", "unknown")
            print(f"[{status.upper()}] {formula}: PBE gap = {pbe_gap} eV ({gap_type}) in {dt:.1f}s\n")
            results[formula] = {
                "formula": formula,
                "a_cubic_angstrom": meta["a_cubic_angstrom"],
                "citation": meta["citation"],
                "target_exp_gap_eV": meta["target_exp_gap_eV"],
                "pbe_gap_eV": round(float(pbe_gap), 4) if pbe_gap is not None else None,
                "gap_type": gap_type,
                "runtime_seconds": round(dt, 2),
                "status": status,
                "poscar": poscar_str,
            }
            with open(results_path, "w", encoding="utf-8") as f:
                json.dump(results, f, indent=2)

    return results


def compute_loocv(dataset_records, name: str):
    """Compute exact LOOCV MAE, RMSE, and conformal quantile for a dataset."""
    n = len(dataset_records)
    pbes = np.array([r["pbe"] for r in dataset_records])
    targets = np.array([r["target"] for r in dataset_records])
    y_delta = targets - pbes
    formulas = [r["formula"] for r in dataset_records]

    # Features: [pbe, pbe^2, chi_diff, r_ratio, Z_avg] (deployed model feature set without eps_inf)
    X = np.array([
        [r["pbe"], r["pbe"]**2, r["chi_diff"], r["r_ratio"], r["Z_avg"]]
        for r in dataset_records
    ])

    loo_errs = []
    loo_preds = []
    query_hs = []

    for i in range(n):
        tr = [j for j in range(n) if j != i]
        sc = StandardScaler()
        Z_tr = sc.fit_transform(X[tr])
        p_dim = Z_tr.shape[1]
        m = Ridge(alpha=1.0, fit_intercept=True)
        m.fit(Z_tr, y_delta[tr])

        Z_te = sc.transform(X[i:i+1])
        pred_d = m.predict(Z_te)[0]
        pred_g = pbes[i] + pred_d
        err = abs(targets[i] - pred_g)
        loo_errs.append(err)
        loo_preds.append(pred_g)

        H_inv = np.linalg.inv(Z_tr.T @ Z_tr + 1.0 * np.eye(p_dim))
        h_q = float((1.0 / len(tr)) + (Z_te @ H_inv @ Z_te.T)[0, 0])
        query_hs.append(h_q)

    mae = float(np.mean(loo_errs))
    rmse = float(np.sqrt(np.mean(np.array(loo_errs)**2)))

    # Conformal 80% and 90%
    # k = ceil((n + 1) * level)
    k_80 = int(np.ceil((n + 1) * 0.80))
    k_90 = int(np.ceil((n + 1) * 0.90))

    norm_scores = [loo_errs[i] / np.sqrt(1.0 + query_hs[i]) for i in range(n)]
    sorted_scores = sorted(norm_scores)

    q_80 = float(sorted_scores[k_80 - 1]) if k_80 <= n else None
    q_90 = float(sorted_scores[k_90 - 1]) if k_90 <= n else None

    print(f"\n================================================================================")
    print(f"LOOCV REPORT: {name} (n={n})")
    print(f"================================================================================")
    print(f"  LOOCV MAE:  {mae:.4f} eV")
    print(f"  LOOCV RMSE: {rmse:.4f} eV")
    print(f"  Conformal 80% Quantile (k={k_80}/{n}): {f'{q_80:.4f} eV' if q_80 is not None else 'UNDEFINED (k > n)'}")
    print(f"  Conformal 90% Quantile (k={k_90}/{n}): {f'{q_90:.4f} eV' if q_90 is not None else 'UNDEFINED (k > n)'}")
    print("  Per-compound LOOCV residuals:")
    for i in range(n):
        print(f"    {formulas[i]:10s} | PBE: {pbes[i]:.4f} eV | Target: {targets[i]:.4f} eV | Pred: {loo_preds[i]:.4f} eV | Residual: {loo_errs[i]:.4f} eV (query h={query_hs[i]:.4f})")
    print("================================================================================\n")

    return {
        "name": name,
        "n": n,
        "mae": round(mae, 4),
        "rmse": round(rmse, 4),
        "k_80": k_80,
        "q_80": round(q_80, 4) if q_80 is not None else None,
        "k_90": k_90,
        "q_90": round(q_90, 4) if q_90 is not None else None,
        "residuals": {formulas[i]: round(loo_errs[i], 4) for i in range(n)}
    }


def main():
    mapb_res = run_or_load_mapb_qe(force_rerun=False)

    # Base CsPbX3 records (from verified pipeline QE)
    cspb_records = [
        {"formula": "CsPbI3", "pbe": 1.3230, "target": 1.73, "chi_diff": 1.87, "r_ratio": 0.5385, "Z_avg": 59.2},
        {"formula": "CsPbBr3", "pbe": 1.5320, "target": 2.36, "chi_diff": 2.17, "r_ratio": 0.4423, "Z_avg": 48.4},
        {"formula": "CsPbCl3", "pbe": 1.9190, "target": 2.85, "chi_diff": 2.37, "r_ratio": 0.3846, "Z_avg": 37.6},
    ]

    # Choice A: n=6 Pb-only with RECOMPUTED PIPELINE QE at Mosconi geometry
    choice_a_records = list(cspb_records) + [
        {"formula": "MAPbI3", "pbe": mapb_res["MAPbI3"]["pbe_gap_eV"], "target": 1.57, "chi_diff": 0.33, "r_ratio": 0.6452, "Z_avg": 52.0},
        {"formula": "MAPbBr3", "pbe": mapb_res["MAPbBr3"]["pbe_gap_eV"], "target": 2.33, "chi_diff": 0.63, "r_ratio": 0.5300, "Z_avg": 41.2},
        {"formula": "MAPbCl3", "pbe": mapb_res["MAPbCl3"]["pbe_gap_eV"], "target": 3.11, "chi_diff": 0.83, "r_ratio": 0.4608, "Z_avg": 30.4},
    ]

    # Choice B: n=6 Pb-only with MOSCONI LITERATURE PBE (1.57 / 1.80 / 2.34 eV)
    choice_b_records = list(cspb_records) + [
        {"formula": "MAPbI3", "pbe": 1.5700, "target": 1.57, "chi_diff": 0.33, "r_ratio": 0.6452, "Z_avg": 52.0},
        {"formula": "MAPbBr3", "pbe": 1.8000, "target": 2.33, "chi_diff": 0.63, "r_ratio": 0.5300, "Z_avg": 41.2},
        {"formula": "MAPbCl3", "pbe": 2.3400, "target": 3.11, "chi_diff": 0.83, "r_ratio": 0.4608, "Z_avg": 30.4},
    ]

    # Choice C: Dropping MAPbX3 entirely (n=3 CsPbX3 only)
    choice_c_records = list(cspb_records)

    # Choice D: n=7 (Choice A + CsSnCl3)
    choice_d_records = list(choice_a_records) + [
        {"formula": "CsSnCl3", "pbe": 0.7990, "target": 2.60, "chi_diff": 2.37, "r_ratio": 0.3846, "Z_avg": 31.2}
    ]

    # Run evaluations
    res_a = compute_loocv(choice_a_records, "Choice A: Deployed Pb-only (n=6) with Recomputed Pipeline QE")
    res_b = compute_loocv(choice_b_records, "Choice B: Pb-only (n=6) with Mosconi Literature PBE (1.57/1.80/2.34)")
    res_c = compute_loocv(choice_c_records, "Choice C: Inorganic-only (n=3 CsPbX3, dropping MAPbX3)")
    res_d = compute_loocv(choice_d_records, "Choice D: With CsSnCl3 included (n=7)")


if __name__ == "__main__":
    main()
